version: '3.7'

services:
  turn-server:
    image: bytearts/turn-server
    ports:
      - 3478:3478
      # Encrypted port (TLS)
#     - 5349:5349
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
      # DH params - generate with 4096 bit to improve security
#     - ./dhparams.pem:/etc/ssl/private/dhparams.pem:ro
      # Private key and certificate needed for encryption (TLS)
#     - ./ssl_key.pem:/etc/ssl/private/key.pem:ro
#     - ./ssl_cert.pem:/etc/ssl/private/cert.pem:ro
    restart: unless-stopped
